version: '3.9'

services:
  mustit-blog-db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_DB=mustit
      - POSTGRES_PASSWORD=1033
      - POSTGRES_USER=root
    container_name: mustit-blog-db
    ports:
      - '5432:5432'
    volumes:
      - ./prisma:/prisma
    networks:
      - mustit-blog

  mustit-blog-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mustit-blog-app
    ports:
      - '9900:9900'
    environment:
      - POSTGRES_HOST=mustit-blog-db
    depends_on:
      - mustit-blog-db
    volumes:
      - ./prisma:/app/prisma
    networks:
      - mustit-blog
    command: npx prisma migrate deploy && npm run start:prod
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U root -h mustit-blog-db']
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: on-failure

networks:
  mustit-blog:
    driver: bridge
