version: '3.9'

services:
  mustit-blog-db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_DB=mustit
      - POSTGRES_PASSWORD=1033
      - POSTGRES_USER=root
    container_name: mustit-blog-db
    ports:
      - '5432:5432'
    networks:
      - mustit-blog

  mustit-blog-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mustit-blog-app
    ports:
      - '3000:3000'
    environment:
      - POSTGRES_HOST=mustit-blog-db
    depends_on:
      - mustit-blog-db
    networks:
      - mustit-blog

  nginx:
    image: nginx:latest
    container_name: mustit-blog-nginx
    ports:
      - '80:80'
    depends_on:
      - mustit-blog-app
    networks:
      - mustit-blog

networks:
  mustit-blog:
